name: NodeJS with Webpack

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Codegen
        run: bun run generate:graphql

      - name: Run the tests
        run: bun run test

      - name: Build
        run: bun run build
        env:
          CI: false

  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Make env file for production
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_APP_DOMAIN: ${{ secrets.VITE_APP_DOMAIN }}
          envkey_VITE_APP_KEYCLOAK_URL: ${{ secrets.VITE_APP_KEYCLOAK_URL }}
          envkey_VITE_APP_BACKEND_URL: ${{ secrets.VITE_APP_BACKEND_URL }}
          directory: .
          file_name: .env.production
          fail_on_empty: true
          sort_keys: false
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/${{ matrix.architecture }}
          tags: xcodeassociated/react-typescript-vite-template_${{ matrix.architecture }}:latest
